version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566-4584:4566-4584"
      - "${PORT_WEB_UI-8000}:${PORT_WEB_UI-8000}"
    environment:
      - SERVICES=s3
      - EDGE_PORT=4566
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"